import { Market, Activity } from '@/types';

export const markets: Market[] = [
  {
    id: '1',
    title: 'Ethereum ETF Approval',
    subtitle: 'SEC approves spot ETH ETF by Q1 2026',
    category: 'Regulation',
    endDate: 'Mar 31, 2026',
    volume: '$2.4M',
    traders: 1847,
    yesPrice: 67,
    noPrice: 33,
    change: 5.2,
    status: 'live',
    description: 'Will the U.S. Securities and Exchange Commission approve a spot Ethereum ETF by the end of Q1 2026?',
    resolution: "This market will resolve to 'Yes' if the SEC approves at least one spot Ethereum ETF for trading on a U.S. exchange by March 31, 2026, 11:59 PM ET.",
    history: [45, 48, 52, 49, 55, 58, 62, 59, 63, 67],
  },
  {
    id: '2',
    title: 'Aleo Mainnet TVL',
    subtitle: 'TVL exceeds $500M by June 2026',
    category: 'DeFi',
    endDate: 'Jun 30, 2026',
    volume: '$890K',
    traders: 634,
    yesPrice: 42,
    noPrice: 58,
    change: -2.8,
    status: 'live',
    description: "Will the total value locked in Aleo's DeFi ecosystem exceed $500 million USD?",
    resolution: "This market resolves to 'Yes' if DefiLlama reports Aleo TVL above $500M at any point before June 30, 2026.",
    history: [55, 52, 48, 50, 46, 44, 45, 43, 44, 42],
  },
  {
    id: '3',
    title: 'Bitcoin $150K',
    subtitle: 'BTC reaches $150,000 in 2026',
    category: 'Price',
    endDate: 'Dec 31, 2026',
    volume: '$5.1M',
    traders: 3291,
    yesPrice: 38,
    noPrice: 62,
    change: 1.4,
    status: 'live',
    description: 'Will Bitcoin reach a price of $150,000 USD or higher at any point during 2026?',
    resolution: "Resolves 'Yes' if BTC/USD reaches $150,000 on Coinbase, Binance, or Kraken before December 31, 2026.",
    history: [32, 35, 33, 36, 38, 35, 37, 36, 37, 38],
  },
  {
    id: '4',
    title: 'Solana Outage',
    subtitle: 'No network outages in Q1 2026',
    category: 'Network',
    endDate: 'Mar 31, 2026',
    volume: '$445K',
    traders: 412,
    yesPrice: 54,
    noPrice: 46,
    change: 0.8,
    status: 'upcoming',
    description: 'Will Solana maintain 100% uptime with no network outages exceeding 1 hour in Q1 2026?',
    resolution: "Resolves 'Yes' if Solana has no documented network outages lasting more than 60 minutes between Jan 1 and Mar 31, 2026.",
    history: [50, 51, 52, 53, 52, 54, 53, 54, 53, 54],
  },
  {
    id: '5',
    title: 'zkSync Token Launch',
    subtitle: 'ZK token airdrop before April',
    category: 'Token',
    endDate: 'Apr 1, 2026',
    volume: '$1.2M',
    traders: 2156,
    yesPrice: 78,
    noPrice: 22,
    change: 8.3,
    status: 'live',
    description: 'Will Matter Labs launch the ZK token and conduct an airdrop to users before April 2026?',
    resolution: "This market resolves 'Yes' if the ZK token is officially launched and tradeable on major exchanges by April 1, 2026.",
    history: [62, 65, 68, 70, 72, 71, 74, 76, 77, 78],
  },
  {
    id: '6',
    title: 'Uniswap v4 Launch',
    subtitle: 'V4 deploys on mainnet Q1 2026',
    category: 'DeFi',
    endDate: 'Mar 31, 2026',
    volume: '$678K',
    traders: 891,
    yesPrice: 85,
    noPrice: 15,
    change: 2.1,
    status: 'live',
    description: 'Will Uniswap v4 be deployed on Ethereum mainnet by the end of Q1 2026?',
    resolution: "Resolves 'Yes' if Uniswap v4 contracts are deployed and functional on Ethereum mainnet by March 31, 2026.",
    history: [75, 77, 78, 80, 81, 82, 83, 84, 84, 85],
  },
  {
    id: '7',
    title: 'Aleo ZK Proving',
    subtitle: 'Sub-second proofs by Q2 2026',
    category: 'Technology',
    endDate: 'Jun 30, 2026',
    volume: '$234K',
    traders: 287,
    yesPrice: 61,
    noPrice: 39,
    change: 4.5,
    status: 'upcoming',
    description: 'Will Aleo achieve sub-second zero-knowledge proof generation for standard transactions?',
    resolution: "Resolves 'Yes' if Aleo demonstrates sub-1-second proof generation in a public benchmark by June 30, 2026.",
    history: [48, 50, 52, 54, 55, 57, 58, 59, 60, 61],
  },
  {
    id: '8',
    title: 'ETH Staking Rate',
    subtitle: 'Staking APY below 3% by Q2',
    category: 'Staking',
    endDate: 'Jun 30, 2026',
    volume: '$567K',
    traders: 723,
    yesPrice: 29,
    noPrice: 71,
    change: -1.2,
    status: 'live',
    description: 'Will the Ethereum staking APY drop below 3% at any point in Q2 2026?',
    resolution: "Resolves 'Yes' if the average ETH staking rate on Lido falls below 3% for at least 7 consecutive days.",
    history: [35, 34, 33, 32, 31, 30, 31, 30, 29, 29],
  },
  {
    id: '9',
    title: 'Base Chain Dominance',
    subtitle: 'Base becomes #1 L2 by TVL',
    category: 'Layer 2',
    endDate: 'Jun 30, 2026',
    volume: '$1.8M',
    traders: 1543,
    yesPrice: 52,
    noPrice: 48,
    change: 6.7,
    status: 'live',
    description: 'Will Base overtake Arbitrum to become the largest L2 by total value locked?',
    resolution: "Resolves 'Yes' if Base TVL exceeds Arbitrum TVL according to L2Beat for at least 24 hours before June 30, 2026.",
    history: [38, 40, 42, 44, 45, 47, 48, 50, 51, 52],
  },
];

export const mockActivities: Activity[] = [
  { user: '0x7a3...f2e', action: 'bought', type: 'yes', amount: '$250', time: '2m ago' },
  { user: '0x9c1...a8b', action: 'sold', type: 'no', amount: '$180', time: '5m ago' },
  { user: '0x2d4...e7c', action: 'bought', type: 'yes', amount: '$500', time: '12m ago' },
  { user: '0x5f8...b3d', action: 'bought', type: 'no', amount: '$320', time: '18m ago' },
];

export const platformStats = {
  totalVolume: '$14.7M',
  activeTraders: 12847,
  totalMarkets: markets.length,
  zkPrivacy: '100%',
};
